/**
 *
 * This file is auto-generated. Do not edit manually: changes may be erased.
 * Generated by Aqua compiler: https://github.com/fluencelabs/aqua/.
 * If you find any bugs, please write an issue on GitHub: https://github.com/fluencelabs/aqua/issues
 * Aqua version: 0.7.4-322
 *
 */
import { Fluence, FluencePeer } from '@fluencelabs/fluence';
import {
    CallParams,
    callFunction,
    registerService,
} from '@fluencelabs/fluence/dist/internal/compilerSupport/v3';


// Services

export interface AccountServiceDef {
    createAccount: (callParams: CallParams<null>) => { address: string; privateKey: string; } | Promise<{ address: string; privateKey: string; }>;
    login: (signatureObject: { messageHash: string; r: string; s: string; v: string; }, privateKey: string, callParams: CallParams<'signatureObject' | 'privateKey'>) => boolean | Promise<boolean>;
}
export function registerAccountService(service: AccountServiceDef): void;
export function registerAccountService(serviceId: string, service: AccountServiceDef): void;
export function registerAccountService(peer: FluencePeer, service: AccountServiceDef): void;
export function registerAccountService(peer: FluencePeer, serviceId: string, service: AccountServiceDef): void;
       

export function registerAccountService(...args: any) {
    registerService(
        args,
        {
    "defaultServiceId" : "AccountService",
    "functions" : {
        "tag" : "labeledProduct",
        "fields" : {
            "createAccount" : {
                "tag" : "arrow",
                "domain" : {
                    "tag" : "nil"
                },
                "codomain" : {
                    "tag" : "unlabeledProduct",
                    "items" : [
                        {
                            "tag" : "struct",
                            "name" : "User",
                            "fields" : {
                                "address" : {
                                    "tag" : "scalar",
                                    "name" : "string"
                                },
                                "privateKey" : {
                                    "tag" : "scalar",
                                    "name" : "string"
                                }
                            }
                        }
                    ]
                }
            },
            "login" : {
                "tag" : "arrow",
                "domain" : {
                    "tag" : "labeledProduct",
                    "fields" : {
                        "signatureObject" : {
                            "tag" : "struct",
                            "name" : "SignatureObject",
                            "fields" : {
                                "messageHash" : {
                                    "tag" : "scalar",
                                    "name" : "string"
                                },
                                "r" : {
                                    "tag" : "scalar",
                                    "name" : "string"
                                },
                                "s" : {
                                    "tag" : "scalar",
                                    "name" : "string"
                                },
                                "v" : {
                                    "tag" : "scalar",
                                    "name" : "string"
                                }
                            }
                        },
                        "privateKey" : {
                            "tag" : "scalar",
                            "name" : "string"
                        }
                    }
                },
                "codomain" : {
                    "tag" : "unlabeledProduct",
                    "items" : [
                        {
                            "tag" : "scalar",
                            "name" : "bool"
                        }
                    ]
                }
            }
        }
    }
}
    );
}
      
// Functions

