/**
 *
 * This file is auto-generated. Do not edit manually: changes may be erased.
 * Generated by Aqua compiler: https://github.com/fluencelabs/aqua/.
 * If you find any bugs, please write an issue on GitHub: https://github.com/fluencelabs/aqua/issues
 * Aqua version: 0.7.4-322
 *
 */
import { Fluence, FluencePeer } from '@fluencelabs/fluence';
import {
    CallParams,
    callFunction,
    registerService,
} from '@fluencelabs/fluence/dist/internal/compilerSupport/v3';


// Services

export interface EventServiceDef {
    emitEvent: (event: string, callParams: CallParams<'event'>) => void | Promise<void>;
    registerEvent: (event: string, callParams: CallParams<'event'>) => void | Promise<void>;
}
export function registerEventService(service: EventServiceDef): void;
export function registerEventService(serviceId: string, service: EventServiceDef): void;
export function registerEventService(peer: FluencePeer, service: EventServiceDef): void;
export function registerEventService(peer: FluencePeer, serviceId: string, service: EventServiceDef): void;
       

export function registerEventService(...args: any) {
    registerService(
        args,
        {
    "defaultServiceId" : "Events_service",
    "functions" : {
        "tag" : "labeledProduct",
        "fields" : {
            "emitEvent" : {
                "tag" : "arrow",
                "domain" : {
                    "tag" : "labeledProduct",
                    "fields" : {
                        "event" : {
                            "tag" : "scalar",
                            "name" : "string"
                        }
                    }
                },
                "codomain" : {
                    "tag" : "nil"
                }
            },
            "registerEvent" : {
                "tag" : "arrow",
                "domain" : {
                    "tag" : "labeledProduct",
                    "fields" : {
                        "event" : {
                            "tag" : "scalar",
                            "name" : "string"
                        }
                    }
                },
                "codomain" : {
                    "tag" : "nil"
                }
            }
        }
    }
}
    );
}
      
// Functions

